<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_database_app_description'] = 'Отчет баз данных предоставляет стандартный набор инструментов для работы с отчетами на основе баз данных.';
$lang['reports_database_app_name'] = 'Отчет базы данных';
