#!/bin/sh

# Sudoers
#--------

/usr/sbin/addsudo /usr/sbin/initialize-report-tables app-reports-database-core

# Bootstrap
#----------

/usr/clearos/apps/reports_database/deploy/initialize-database >/dev/null 2>&1
