<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_database_app_description'] = 'The Reports Database provides a common set of tools for managing database-driven reports.';
$lang['reports_database_app_name'] = 'Reports Database';
