<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_database_app_description'] = 'Rapportdatabasen ger dig ett gemensam verktygsuppsättning för att hantera databasdrivna rapporter.';
$lang['reports_database_app_name'] = 'Rapportdatabas';
