#!/bin/sh

APP_DB=$1
APP_DB_TABLES=$2

MYSQL="/usr/clearos/sandbox/usr/bin/mysql"
DB_CONFIG="/var/clearos/system_database/root"

# Start system database
#----------------------

/usr/clearos/apps/system_database/deploy/bootstrap

# Grab root database password
#----------------------------

ROOTPASS=`grep ^password $DB_CONFIG 2>/dev/null | sed "s/^password[[:space:]]*=[[:space:]]*//"`

if [ -z "$ROOTPASS" ]; then
    echo "Unable to authenticate with database"
    exit 1
fi

# Create tables (if necessary)
#-----------------------------

TABLE_EXISTS=`$MYSQL -uroot -p"$ROOTPASS" -e 'show tables;' reports 2>/dev/null | grep $APP_DB`

if [ -z "$TABLE_EXISTS" ]; then
    logger -p local6.notice -t installer "app-reports-database-core - creating tables for $APP_DB"
    $MYSQL -uroot -p"$ROOTPASS" reports < $APP_DB_TABLES
fi
