#!/bin/sh

DBINFO="/var/clearos/system_database/reports"
MYSQL="/usr/clearos/sandbox/usr/bin/mysql"

# Sanity check app name
#----------------------

if [ -z "$1" ]; then
    echo "Basename required, e.g. network, resource"
    exit 1
fi

BASENAME="$1"
REPORT_NAME="${1}_report"
REPORT_CONFIG="/etc/clearos/${REPORT_NAME}.conf"

if [ ! -e "/usr/clearos/apps/$REPORT_NAME/deploy/info.php" ]; then
    echo "Report is not installed: $REPORT_NAME"
    exit 1
fi

# Check database status
#----------------------

[ -e /var/lib/system-mysql/mysql.sock ] || exit 0

# Grab the number of records to keep
#-----------------------------------

RECORDS=`grep ^records $REPORT_CONFIG 2>/dev/null | sed 's/.*=//'`
if [ -z "$RECORDS" ]; then
	RECORDS=200000
fi

# Grab database password
#-----------------------

DBPASS=`grep ^password $DBINFO 2>/dev/null | sed "s/^password[[:space:]]*=[[:space:]]*//"`

if [ -z "$DBPASS" ]; then
    echo "Unable to authenticate with database"
    exit 1
fi

# Purge database
#---------------

$MYSQL -ureports -p"$DBPASS" -e "\
DROP TABLE IF EXISTS ${BASENAME}_prune; \
CREATE TABLE ${BASENAME}_prune SELECT * FROM $BASENAME ORDER BY timestamp DESC LIMIT $RECORDS; \
RENAME TABLE ${BASENAME} TO ${BASENAME}_old, ${BASENAME}_prune TO ${BASENAME};  \
DROP TABLE ${BASENAME}_old; \
" reports
