<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_database_app_description'] = 'Baza raportów udostępnia często wykorzystywane zestawy narzędzi do zarządzania raportami.';
$lang['reports_database_app_name'] = 'Baza raportów';
