<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['reports_database_app_description'] = 'Baza raportów dostarcza wspólne zestawy narzędzi do zarządzania raportami opartymi o bazę danych.';
$lang['reports_database_app_name'] = 'Baza raportów';
